# This configuration sets the node linker to use the traditional node_modules structure.
# This means Yarn will create a node_modules directory and place all dependencies there.
nodeLinker: node-modules

# This configuration specifies the path to the specific Yarn version to be used for this project.
# The specified version is 3.6.4, and the path is relative to the project's root directory.
yarnPath: .yarn/releases/yarn-3.6.4.cjs
